const translations = {
  serverRunning: "Server is running on port",
  dbConnect: "Connected to MongoDB",
  dbError: "Couldn't connect to db",
  firstNameRequired: "firstName is required",
  lastNameRequired: "lastName is required",
  emailRequired: "email is required",
  passwordRequired: "password is required",
  roleRequired: "role is required",
  registerFail: "User registration failed",
  registerSuccess: "User registered successfully",
  fillDetails: "Please fill all details",
  internalError: "Internal Server Error",
  loginSuccess: "Login successful",
  userNotFound: "User doesn't exist",
  passwordNotMatch: "Password does not match",
  unAuthorize: "User not authorized to proceed!!",
  noToken: "No token provided, please login first!",
  InvalidToken: "Invalid token",
  surveyCreated: "Survey created successfully",
  surveyDeleted: "Survey deleted successfully",
  surveyUpdated: "Survey updated successfully",
  surveyList: "Surveys retrieved successfully",
  surveyFound: "Survey found successfully",
  surveyNotFound: "Survey not found",
  surveyCreationFailed: "Not able to create survey",
  surveyUpdateFailed: "Not able to update survey",
  surveyDeletionFailed: "Not able to delete survey",
  titleRequired: "Title is required for the survey",
  questionRequired: "At least one question is required for the survey",
  responseList: "Response list fetched successfully",
  responseCreated: "Response created successfully",
  responseNotFound: "Response not found",
  responseFound: " Response found successfully",
  responseDeleted: "Response deleted successfully",
  responseCreationFailed: "Not able to create response",
  responseUpdated: "Response updated successfully",
  responseUpdateFailed: "Not able to update response",
  responseDeletionFailed: "Not able to delete response",
  unauthorized: "Unauthorized access",
};

export default translations;
